title: EnsiNet
description: > 
  Esta é a nossa plataforma de publicação do Trabalho de Conclusão
  de Série (TCS) do Colégio Objetivo Baixada. Com o objetivo de
  estimular o estudo e a pesquisa, identificar estudantes talentosos
  e estimulá-los ao aprimoramento contínuo das ciências e tecnologias,
  desenvolver o pensamento autônomo e crítico e estimular o trabalho
  investigativo e colaborativo.
baseurl: "/EnsiNet"
url: "http://objetivoweb.github.io"
semestre: "2017-1"

markdown: kramdown

gems:
  - jekyll-coffeescript

exclude:
  - gulpfile.js
  - README.md
  - desktop.ini

collections:
  areas:
    output: true
  unidades:
    output: true
  projetos:
    output: true

defaults:
  - scope:
      path: ""
      type: areas
    values:
      layout: area
  - scope:
      path: ""
      type: unidades
    values:
      layout: unidade
  - scope:
      path: ""
      type: projetos
    values:
      layout: projeto
